# Makefile
# makefile for figs

TARGET=jaya-004.png jaya-008.png jaya-011.png jaya-015.png jaya-021.png jaya-022.png jaya-026.png olu-003.png olu-004.png olu-005.png olu-008.png

FORCE:
	make $(TARGET)

%.png: %.ppm
	convert $< $@


# eof
