#!/bin/sh
# /etc/init.d/sayIPbs
## Some things that run always
# Carry out specific functions when asked to by the system
case "$1" in  start)
    echo "Starting script sayIPbs "
    sleep 5
    public=`curl ifconfig.me`
    private=`hostname -I`
    string="public address is $public and private address is $private"
    echo $string | espeak -s 120 -v en-uk
    sleep 2
    echo $string | espeak -s 120 -v en-uk
    ;;  stop)    
echo "Stopping script sayIPbs"
    ;;  *)
    echo "Usage: /etc/init.d/sayIPbs {start|stop}"
    exit 1
    ;;esac
exit 0


